#!/bin/sh

# set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 <path_to_map_file> <path_to_output_file>"
    exit 1
fi

mapfile="$1"
outputfile="$2"

{
    echo "// !!! THIS FILE IS AUTOGENERATED !!!"
    echo "#include <structs/symbols_str.h>"
    echo "const SYMBOL _kernel_symbols[] = {"

    awk '
    BEGIN {
        IGNORECASE = 0
    }
    /^[[:space:]]*0x[0-9a-fA-F]{16}[[:space:]]+[_a-zA-Z][_a-zA-Z0-9]*$/ {
        addr = $1
        name = $2
        printf "    { .addr = %s, .name = \"%s\" },\n", addr, name
    }
    /^\.data/ || /^\.rodata/ {
        exit
    }
    ' "$mapfile"

    echo "};"
} > "$outputfile"
