#!/bin/bash

# Check for input arguments: map file and output file
if [ $# -ne 2 ]; then
    echo "Usage: $0 <path_to_map_file> <path_to_output_file>"
    exit 1
fi

# Paths for the map file and the output header file
mapfile="$1"
outputfile="$2"

# Create a temporary file to store the new output
# tempfile=$(mktemp)

# Begin writing to the temporary file
{
echo "// !!! THIS FILE IS AUTOGENERATED !!!"
echo "#include <structs/symbols_str.h>"
echo "const SYMBOL _kernel_symbols[] = {"

# Read the map file line-by-line
while IFS= read -r line; do
    # Match lines with an address followed by a function name
    if [[ $line =~ ^[[:space:]]*(0x[0-9a-fA-F]{16})[[:space:]]+([_a-zA-Z][_a-zA-Z0-9]*)$ ]]; then
        # Extract the address and function name from the matched groups
        addr="${BASH_REMATCH[1]}"
        func_name="${BASH_REMATCH[2]}"

        # Print the entry in the desired format
        echo "    { .addr = $addr, .name = \"$func_name\" },"
    elif [[ $line =~ ^.data ]]; then
        # If we've made it to the .data section, exit
        break
    elif [[ $line =~ ^.rodata ]]; then
        # If we've made it to the .rodata section, exit
        break
    fi
done < "$mapfile"

# End the output
echo "};"

# } > "$tempfile"
} > "$outputfile"

# # Compare checksums of the output file and the temporary file
# if [ -f "$outputfile" ]; then
#     # Check if the checksums are the same
#     checksum_original=$(sha256sum "$outputfile" | awk '{print $1}')
#     checksum_temp=$(sha256sum "$tempfile" | awk '{print $1}')

#     if [ "$checksum_original" == "$checksum_temp" ]; then
#         # If checksums are the same, remove the temporary file and return 1
#         rm "$tempfile"
#         exit 1
#     fi
# fi

# # Replace the existing output file with the temporary file and remove the temporary file
# mv "$tempfile" "$outputfile"
# exit 0
